name: Update Fork

on:
  schedule:
    - cron: '0 0 * * *' # Запуск каждый день в полночь по UTC
  workflow_dispatch: # Возможность запуска вручную через интерфейс GitHub

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main # Убедитесь, что используете правильную основную ветку
          token: ${{ secrets.PAT_TOKEN }} # Использование вашего личного токена

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Setup Upstream
        run: |
          git remote add upstream https://github.com/JKorf/Mexc.Net.git || git remote set-url upstream https://github.com/JKorf/Mexc.Net.git

      - name: Fetch Upstream and Merge
        run: |
          git fetch upstream
          git checkout main
          git merge upstream/main --strategy-option theirs || true

      - name: Check for Changes
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
            exit 0
          fi

      - name: Push Changes
        run: |
          git push origin main
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }} # Использование вашего личного токена
          commit-message: Update fork from upstream
          title: Sync with upstream
          body: |
            This is an automated pull request generated by GitHub Actions to keep your fork up-to-date with the upstream repository.
          branch: update-fork

      - name: Cleanup Temporary Branch
        run: |
          git push origin --delete update-fork || true
