name: Auto-create PR from upstream

on:
  push:
    branches: [ main ]  # Замените 'main' на вашу основную ветку

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Git config
        run: |
          git config --global user.email "your_email@example.com"
          git config --global user.name "Your Name"
      - name: Fetch upstream changes
        run: git fetch upstream
      - name: Checkout and merge upstream changes
        run: |
          git checkout -b https://github.com/JKorf/Mexc.Net.git
          git merge upstream/main
      - name: Push changes to your fork
        run: git push origin https://github.com/JKorf/Mexc.Net.git
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Update from upstream
          body: Automatically created PR
          head: https://github.com/JKorf/Mexc.Net.git
          base: main
