name: Update Fork

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main # Убедитесь, что используете правильную основную ветку
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git remote add upstream https://github.com/JKorf/Mexc.Net.git

      - name: Fetch Upstream
        run: |
          git fetch upstream
          git checkout main
          git merge upstream/main

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: Update fork from upstream
          title: Sync with upstream
          body: |
            This is an automated pull request generated by GitHub Actions to keep your fork up-to-date with the upstream repository.
          branch: update-fork

      - name: Cleanup Temporary Branch
        run: |
          git push origin --delete update-fork || true
